[package]

name = "rust-zlib"
version = "0.0.1"
authors = ["Francis Nimick <fnimick@gmail.com>"]
build = "build.rs"
links = "miniz"

[build-dependencies]
gcc = "= 0.1.5"

[lib]
name = "rzlib"
crate-type = ["staticlib"]
